[phabricator] Fix failing tests
Python3 does not allow deletion of items while iterating
the dictionary which is causing RuntimeError.
RuntimeError: dictionary changed size during iteration

This code fixes the failing tests.

Signed-off-by: Venu Vardhan Reddy Tekula <venu@bitergia.com>