[ocean][git] Map data.message to string so it is not a keyword because it is large field (>32K) in some cases
In some gits the exception raised is:

java.lang.IllegalArgumentException: Document contains at least one immense term in field="data.message"