[enriched/github] Fix unexpected keyword argument 'alias' in onion
This code fixes TypeError in github pull requests category since
the name of the aliases is no longer harcoded, now it is passed by
parameter.

Error:
```
TypeError: enrich_onion() got an unexpected keyword argument 'alias'
```

Test added accordingly.

Signed-off-by: Quan Zhou <quan@bitergia.com>